import { Link } from "react-router-dom";
import { useParams } from "react-router-dom";

const Products = () => {
  const allProducts = [
    {
      id: 1,
      name: "Dress1",
      category: "Dress",
      image: "/src/assets/images/ima1.jpg",
      price: 29.99,
      description: "Description for Dress 1",
      features: ["Feature 1", "Feature 2"],
      gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
    },
    {
      id: 2,
      name: "Dress2",
      category: "Dress",
      image: "/src/assets/images/ima2.jpg",
      price: 49.99,
      description: "Description for Dress 2",
      features: ["Feature 1", "Feature 2"],
      gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
    },
    {
      id: 3,
      name: "Dress3",
      category: "Dress",
      image: "/src/assets/images/ima3.jpg",
      price: 29.99,
      description: "Description for Dress 3",
      features: ["Feature 1", "Feature 2"],
      gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
    },
    {
      id: 4,
      name: "Dress4",
      category: "Dress",
      image: "/src/assets/images/ima4.jpg",
      price: 49.99,
      description: "Description for Dress 4",
      features: ["Feature 1", "Feature 2"],
      gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
    },
    {
      id: 5,
      name: "Dress5",
      category: "Dress",
      image: "/src/assets/images/ima5.jpg",
      price: 29.99,
      description: "Description for Dress 5",
      features: ["Feature 1", "Feature 2"],
      gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
    },
    {
      id: 6,
      name: "Dress6",
      category: "Dress",
      image: "/src/assets/images/ima6.jpg",
      price: 49.99,
      description: "Description for Dress 6",
      features: ["Feature 1", "Feature 2"],
      gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
    },
    {
      id: 1,
      name: "Mobiles1",
      category: "Mobiles",
      image: "/src/assets/images/ima1.jpg",
      price: 29.99,
      description: "Description for Mobiles 1",
      features: ["Feature 1", "Feature 2"],
      gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
    },
    {
      id: 2,
      name: "Mobiles2",
      category: "Mobiles",
      image: "/src/assets/images/ima2.jpg",
      price: 49.99,
      description: "Description for Mobiles 2",
      features: ["Feature 1", "Feature 2"],
      gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
    },
    {
      id: 3,
      name: "Mobiles3",
      category: "Mobiles",
      image: "/src/assets/images/ima3.jpg",
      price: 29.99,
      description: "Description for Mobiles 3",
      features: ["Feature 1", "Feature 2"],
      gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
    },
    {
      id: 4,
      name: "Mobiles4",
      category: "Mobiles",
      image: "/src/assets/images/ima4.jpg",
      price: 49.99,
      description: "Description for Mobiles 4",
      features: ["Feature 1", "Feature 2"],
      gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
    },
    {
      id: 5,
      name: "Mobiles5",
      category: "Mobiles",
      image: "/src/assets/images/ima5.jpg",
      price: 29.99,
      description: "Description for Mobiles 5",
      features: ["Feature 1", "Feature 2"],
      gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
    },
    {
      id: 6,
      name: "Mobiles6",
      category: "Mobiles",
      image: "/src/assets/images/ima6.jpg",
      price: 49.99,
      description: "Description for Mobiles 6",
      features: ["Feature 1", "Feature 2"],
      gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
    },
    {
      id: 1,
      name: "Laptops1",
      category: "Laptops",
      image: "/src/assets/images/ima1.jpg",
      price: 29.99,
      description: "Description for Laptops 1",
      features: ["Feature 1", "Feature 2"],
      gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
    },
    {
      id: 2,
      name: "Laptops2",
      category: "Laptops",
      image: "/src/assets/images/ima2.jpg",
      price: 49.99,
      description: "Description for Laptops 2",
      features: ["Feature 1", "Feature 2"],
      gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
    },
    {
      id: 3,
      name: "Laptops3",
      category: "Laptops",
      image: "/src/assets/images/ima3.jpg",
      price: 29.99,
      description: "Description for Laptops 3",
      features: ["Feature 1", "Feature 2"],
      gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
    },
    {
      id: 4,
      name: "Laptops4",
      category: "Laptops",
      image: "/src/assets/images/ima4.jpg",
      price: 49.99,
      description: "Description for Laptops 4",
      features: ["Feature 1", "Feature 2"],
      gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
    },
    {
      id: 5,
      name: "Laptops5",
      category: "Laptops",
      image: "/src/assets/images/ima5.jpg",
      price: 29.99,
      description: "Description for Laptops 5",
      features: ["Feature 1", "Feature 2"],
      gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
    },
    {
      id: 6,
      name: "Laptops6",
      category: "Laptops",
      image: "/src/assets/images/ima6.jpg",
      price: 49.99,
      description: "Description for Laptops 6",
      features: ["Feature 1", "Feature 2"],
      gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
    },
    {
      id: 1,
      name: "Shoes1",
      category: "Shoes",
      image: "/src/assets/images/ima1.jpg",
      price: 29.99,
      description: "Description for Shoes 1",
      features: ["Feature 1", "Feature 2"],
      gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
    },
    {
      id: 2,
      name: "Shoes2",
      category: "Shoes",
      image: "/src/assets/images/ima2.jpg",
      price: 49.99,
      description: "Description for Shoes 2",
      features: ["Feature 1", "Feature 2"],
      gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
    },
    {
      id: 3,
      name: "Shoes3",
      category: "Shoes",
      image: "/src/assets/images/ima3.jpg",
      price: 29.99,
      description: "Description for Shoes 3",
      features: ["Feature 1", "Feature 2"],
      gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
    },
    {
      id: 4,
      name: "Shoes4",
      category: "Shoes",
      image: "/src/assets/images/ima4.jpg",
      price: 49.99,
      description: "Description for Shoes 4",
      features: ["Feature 1", "Feature 2"],
      gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
    },
    {
      id: 5,
      name: "Shoes5",
      category: "Shoes",
      image: "/src/assets/images/ima5.jpg",
      price: 29.99,
      description: "Description for Shoes 5",
      features: ["Feature 1", "Feature 2"],
      gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
    },
    {
      id: 6,
      name: "Shoes6",
      category: "Shoes",
      image: "/src/assets/images/ima6.jpg",
      price: 49.99,
      description: "Description for Shoes 6",
      features: ["Feature 1", "Feature 2"],
      gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
    },
    {
      id: 1,
      name: "Earphones1",
      category: "Earphones",
      image: "/src/assets/images/ima1.jpg",
      price: 29.99,
      description: "Description for Earphones 1",
      features: ["Feature 1", "Feature 2"],
      gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
    },
    {
      id: 2,
      name: "Earphones2",
      category: "Earphones",
      image: "/src/assets/images/ima2.jpg",
      price: 49.99,
      description: "Description for Earphones 2",
      features: ["Feature 1", "Feature 2"],
      gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
    },
    {
      id: 3,
      name: "Earphones3",
      category: "Earphones",
      image: "/src/assets/images/ima3.jpg",
      price: 29.99,
      description: "Description for Earphones 3",
      features: ["Feature 1", "Feature 2"],
      gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
    },
    {
      id: 4,
      name: "Earphones4",
      category: "Earphones",
      image: "/src/assets/images/ima4.jpg",
      price: 49.99,
      description: "Description for Earphones 4",
      features: ["Feature 1", "Feature 2"],
      gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
    },
    {
      id: 5,
      name: "Earphones5",
      category: "Earphones",
      image: "/src/assets/images/ima5.jpg",
      price: 29.99,
      description: "Description for Earphones 5",
      features: ["Feature 1", "Feature 2"],
      gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
    },
    {
      id: 6,
      name: "Earphones6",
      category: "Earphones",
      image: "/src/assets/images/ima6.jpg",
      price: 49.99,
      description: "Description for Earphones 6",
      features: ["Feature 1", "Feature 2"],
      gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
    },
    {
      id: 1,
      name: "Bikes1",
      category: "Bikes",
      image: "/src/assets/images/ima1.jpg",
      price: 29.99,
      description: "Description for Bikes 1",
      features: ["Feature 1", "Feature 2"],
      gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
    },
    {
      id: 2,
      name: "Bikes2",
      category: "Bikes",
      image: "/src/assets/images/ima2.jpg",
      price: 49.99,
      description: "Description for Bikes 2",
      features: ["Feature 1", "Feature 2"],
      gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
    },
    {
      id: 3,
      name: "Bikes3",
      category: "Bikes",
      image: "/src/assets/images/ima3.jpg",
      price: 29.99,
      description: "Description for Bikes 3",
      features: ["Feature 1", "Feature 2"],
      gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
    },
    {
      id: 4,
      name: "Bikes4",
      category: "Bikes",
      image: "/src/assets/images/ima4.jpg",
      price: 49.99,
      description: "Description for Bikes 4",
      features: ["Feature 1", "Feature 2"],
      gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
    },
    {
      id: 5,
      name: "Bikes5",
      category: "Bikes",
      image: "/src/assets/images/ima5.jpg",
      price: 29.99,
      description: "Description for Bikes 5",
      features: ["Feature 1", "Feature 2"],
      gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
    },
    {
      id: 6,
      name: "Bikes6",
      category: "Bikes",
      image: "/src/assets/images/ima6.jpg",
      price: 49.99,
      description: "Description for Bikes 6",
      features: ["Feature 1", "Feature 2"],
      gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
    },
  ];

  const { categoryId } = useParams(); // Get category ID from route

  const filteredProducts = categoryId
    ? allProducts.filter((product) => product.category === categoryId)
    : allProducts; // Display all products if no category ID
  return (
    <div>
      <section className="products grid grid-cols-1 md:grid-cols-3 gap-4 my-8">
        {filteredProducts.map((product) => (
          <Link key={product.id} to={`/details/${product.name}`}>
            <div
              key={product.id}
              className="product p-4 rounded-md shadow-md bg-black "
            >
              <img
                src={product.image}
                alt={product.name}
                className="w-full h-96 object-fit rounded-t-md"
              />
              <div className="p-4">
                <h2 className="text-white text-lg font-bold">{product.name}</h2>
                <p className="text-white">${product.price}</p>
              </div>
            </div>
          </Link>
        ))}
      </section>
    </div>
  );
};
export default Products;
