import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App.jsx";
import "./index.css";
import { createBrowserRouter, RouterProvider } from "react-router-dom";
import Products from "./components/Products/Products.jsx";
import ProductDetails from "./components/ProductDetails/ProductDetails.jsx";

const allProducts = [
  {
    id: 1,
    name: "Dress1",
    category: "Dress",
    image: "/src/assets/images/ima1.jpg",
    price: 29.99,
    description: "Description for Dress 1",
    features: ["Feature 1", "Feature 2"],
    gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
  },
  {
    id: 2,
    name: "Dress2",
    category: "Dress",
    image: "/src/assets/images/ima2.jpg",
    price: 49.99,
    description: "Description for Dress 2",
    features: ["Feature 1", "Feature 2"],
    gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
  },
  {
    id: 3,
    name: "Dress3",
    category: "Dress",
    image: "/src/assets/images/ima3.jpg",
    price: 29.99,
    description: "Description for Dress 3",
    features: ["Feature 1", "Feature 2"],
    gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
  },
  {
    id: 4,
    name: "Dress4",
    category: "Dress",
    image: "/src/assets/images/ima4.jpg",
    price: 49.99,
    description: "Description for Dress 4",
    features: ["Feature 1", "Feature 2"],
    gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
  },
  {
    id: 5,
    name: "Dress5",
    category: "Dress",
    image: "/src/assets/images/ima5.jpg",
    price: 29.99,
    description: "Description for Dress 5",
    features: ["Feature 1", "Feature 2"],
    gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
  },
  {
    id: 6,
    name: "Dress6",
    category: "Dress",
    image: "/src/assets/images/ima6.jpg",
    price: 49.99,
    description: "Description for Dress 6",
    features: ["Feature 1", "Feature 2"],
    gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
  },
  {
    id: 1,
    name: "Mobiles1",
    category: "Mobiles",
    image: "/src/assets/images/ima1.jpg",
    price: 29.99,
    description: "Description for Mobiles 1",
    features: ["Feature 1", "Feature 2"],
    gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
  },
  {
    id: 2,
    name: "Mobiles2",
    category: "Mobiles",
    image: "/src/assets/images/ima2.jpg",
    price: 49.99,
    description: "Description for Mobiles 2",
    features: ["Feature 1", "Feature 2"],
    gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
  },
  {
    id: 3,
    name: "Mobiles3",
    category: "Mobiles",
    image: "/src/assets/images/ima3.jpg",
    price: 29.99,
    description: "Description for Mobiles 3",
    features: ["Feature 1", "Feature 2"],
    gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
  },
  {
    id: 4,
    name: "Mobiles4",
    category: "Mobiles",
    image: "/src/assets/images/ima4.jpg",
    price: 49.99,
    description: "Description for Mobiles 4",
    features: ["Feature 1", "Feature 2"],
    gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
  },
  {
    id: 5,
    name: "Mobiles5",
    category: "Mobiles",
    image: "/src/assets/images/ima5.jpg",
    price: 29.99,
    description: "Description for Mobiles 5",
    features: ["Feature 1", "Feature 2"],
    gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
  },
  {
    id: 6,
    name: "Mobiles6",
    category: "Mobiles",
    image: "/src/assets/images/ima6.jpg",
    price: 49.99,
    description: "Description for Mobiles 6",
    features: ["Feature 1", "Feature 2"],
    gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
  },
  {
    id: 1,
    name: "Laptops1",
    category: "Laptops",
    image: "/src/assets/images/ima1.jpg",
    price: 29.99,
    description: "Description for Laptops 1",
    features: ["Feature 1", "Feature 2"],
    gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
  },
  {
    id: 2,
    name: "Laptops2",
    category: "Laptops",
    image: "/src/assets/images/ima2.jpg",
    price: 49.99,
    description: "Description for Laptops 2",
    features: ["Feature 1", "Feature 2"],
    gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
  },
  {
    id: 3,
    name: "Laptops3",
    category: "Laptops",
    image: "/src/assets/images/ima3.jpg",
    price: 29.99,
    description: "Description for Laptops 3",
    features: ["Feature 1", "Feature 2"],
    gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
  },
  {
    id: 4,
    name: "Laptops4",
    category: "Laptops",
    image: "/src/assets/images/ima4.jpg",
    price: 49.99,
    description: "Description for Laptops 4",
    features: ["Feature 1", "Feature 2"],
    gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
  },
  {
    id: 5,
    name: "Laptops5",
    category: "Laptops",
    image: "/src/assets/images/ima5.jpg",
    price: 29.99,
    description: "Description for Laptops 5",
    features: ["Feature 1", "Feature 2"],
    gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
  },
  {
    id: 6,
    name: "Laptops6",
    category: "Laptops",
    image: "/src/assets/images/ima6.jpg",
    price: 49.99,
    description: "Description for Laptops 6",
    features: ["Feature 1", "Feature 2"],
    gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
  },
  {
    id: 1,
    name: "Shoes1",
    category: "Shoes",
    image: "/src/assets/images/ima1.jpg",
    price: 29.99,
    description: "Description for Shoes 1",
    features: ["Feature 1", "Feature 2"],
    gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
  },
  {
    id: 2,
    name: "Shoes2",
    category: "Shoes",
    image: "/src/assets/images/ima2.jpg",
    price: 49.99,
    description: "Description for Shoes 2",
    features: ["Feature 1", "Feature 2"],
    gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
  },
  {
    id: 3,
    name: "Shoes3",
    category: "Shoes",
    image: "/src/assets/images/ima3.jpg",
    price: 29.99,
    description: "Description for Shoes 3",
    features: ["Feature 1", "Feature 2"],
    gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
  },
  {
    id: 4,
    name: "Shoes4",
    category: "Shoes",
    image: "/src/assets/images/ima4.jpg",
    price: 49.99,
    description: "Description for Shoes 4",
    features: ["Feature 1", "Feature 2"],
    gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
  },
  {
    id: 5,
    name: "Shoes5",
    category: "Shoes",
    image: "/src/assets/images/ima5.jpg",
    price: 29.99,
    description: "Description for Shoes 5",
    features: ["Feature 1", "Feature 2"],
    gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
  },
  {
    id: 6,
    name: "Shoes6",
    category: "Shoes",
    image: "/src/assets/images/ima6.jpg",
    price: 49.99,
    description: "Description for Shoes 6",
    features: ["Feature 1", "Feature 2"],
    gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
  },
  {
    id: 1,
    name: "Earphones1",
    category: "Earphones",
    image: "/src/assets/images/ima1.jpg",
    price: 29.99,
    description: "Description for Earphones 1",
    features: ["Feature 1", "Feature 2"],
    gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
  },
  {
    id: 2,
    name: "Earphones2",
    category: "Earphones",
    image: "/src/assets/images/ima2.jpg",
    price: 49.99,
    description: "Description for Earphones 2",
    features: ["Feature 1", "Feature 2"],
    gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
  },
  {
    id: 3,
    name: "Earphones3",
    category: "Earphones",
    image: "/src/assets/images/ima3.jpg",
    price: 29.99,
    description: "Description for Earphones 3",
    features: ["Feature 1", "Feature 2"],
    gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
  },
  {
    id: 4,
    name: "Earphones4",
    category: "Earphones",
    image: "/src/assets/images/ima4.jpg",
    price: 49.99,
    description: "Description for Earphones 4",
    features: ["Feature 1", "Feature 2"],
    gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
  },
  {
    id: 5,
    name: "Earphones5",
    category: "Earphones",
    image: "/src/assets/images/ima5.jpg",
    price: 29.99,
    description: "Description for Earphones 5",
    features: ["Feature 1", "Feature 2"],
    gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
  },
  {
    id: 6,
    name: "Earphones6",
    category: "Earphones",
    image: "/src/assets/images/ima6.jpg",
    price: 49.99,
    description: "Description for Earphones 6",
    features: ["Feature 1", "Feature 2"],
    gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
  },
  {
    id: 1,
    name: "Bikes1",
    category: "Bikes",
    image: "/src/assets/images/ima1.jpg",
    price: 29.99,
    description: "Description for Bikes 1",
    features: ["Feature 1", "Feature 2"],
    gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
  },
  {
    id: 2,
    name: "Bikes2",
    category: "Bikes",
    image: "/src/assets/images/ima2.jpg",
    price: 49.99,
    description: "Description for Bikes 2",
    features: ["Feature 1", "Feature 2"],
    gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
  },
  {
    id: 3,
    name: "Bikes3",
    category: "Bikes",
    image: "/src/assets/images/ima3.jpg",
    price: 29.99,
    description: "Description for Bikes 3",
    features: ["Feature 1", "Feature 2"],
    gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
  },
  {
    id: 4,
    name: "Bikes4",
    category: "Bikes",
    image: "/src/assets/images/ima4.jpg",
    price: 49.99,
    description: "Description for Bikes 4",
    features: ["Feature 1", "Feature 2"],
    gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
  },
  {
    id: 5,
    name: "Bikes5",
    category: "Bikes",
    image: "/src/assets/images/ima5.jpg",
    price: 29.99,
    description: "Description for Bikes 5",
    features: ["Feature 1", "Feature 2"],
    gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
  },
  {
    id: 6,
    name: "Bikes6",
    category: "Bikes",
    image: "/src/assets/images/ima6.jpg",
    price: 49.99,
    description: "Description for Bikes 6",
    features: ["Feature 1", "Feature 2"],
    gallery: ["/src/assets/images/ima2.jpg", "/src/assets/images/ima3.jpg"],
  },
];

const router = createBrowserRouter([
  {
    path: "/",
    element: <App />,
  },

  {
    path: "/products/:categoryId",
    element: <Products />,
  },

  {
    path: "/details/:productId",
    element: <ProductDetails allProducts={allProducts} />,
  },
]);

ReactDOM.createRoot(document.getElementById("root")).render(
  <React.StrictMode>
    <RouterProvider router={router} />
  </React.StrictMode>
);
